### ISSUE TITLE
mysql

### ISSUE THREAD

**Issue by gummipunkt** [rmlewisuk/one40#13]
gummipunkt@bierpark:~/one40$ php artisan one40:setup

[Illuminate\Database\QueryException]                                                                                                                                         
  SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes. (SQL: alter table `users` add unique `users_email_unique`(`email`))  
                                                                                                        
  [PDOException]                                                                                           
  SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes.  
                                                                                                           
Server: Ubuntu 16.04.1 LTS

**Comment by rmlewisuk** [comment]
I'm not sure how much I can help with this. It sounds like a Mysql config issue.
